### ISSUE TITLE
[Feature]음원 결제

### ISSUE THREAD

**Issue by MinsuKim21** [UXMUnderGraduate/22-S-Front#11]
**Description**
상세정보 페이지에서 구매버튼을 클릭했을 경우 구매페이지로 넘어간다.

---

**TODO**
- [ ] sweet alert를 통해 구매약관을 보여준다.
- [x] 다음 버튼, 이전 버튼
- [x] 약관 동의버튼
- [x] 결제 버튼
- [ ] 잔액부족에 경우 사용자에게 부족하다고 알린다.

---

**ETC**
기타사항
