### ISSUE TITLE
[Feature] 회원가입

### ISSUE THREAD

**Issue by MinsuKim21** [UXMUnderGraduate/22-S-Front#5]
**Description**
회원가입 페이지

---

**TODO**
- [x] 정규표현식체크(입력시)
- [x] 아이디, 닉네임(아티스트명), 비밀번호, 비밀번호 확인, 가입유형, 지갑주소(메타마스크였나?)
- [ ] 지갑 중복 체크 버튼
- [ ] 중복시 alert 띄움
- [ ] 회원가입 폼을 sweet-alert로 띄움

---

**ETC**
기타사항
