### ISSUE TITLE
[Feature]헤더

### ISSUE THREAD

**Issue by MinsuKim21** [UXMUnderGraduate/22-S-Front#7]
**Description**
헤더제작
---

**TODO**
- [x] 로그인이 안됐다면 로그인/회원가입 페이지 연결 버튼
- [x] 사이트이름, 로고는 클릭시 메인페이지 이동

**헤더내용**
- [x] 로고 
- [x] 홈
- [x] Library(내가 구매한 곡 정보 페이지)
- [x] 서치바
- [x] Upload(업로드페이지)
- [x] 프로필 (로그인하면 닉네임을 띄운다)
- [x] 알림 (구매기록이 뜰 예정임)
- [x] 케밥 매뉴 

---

**ETC**
참고 이미지
<img width="1250" alt="스크린샷 2022-07-30 22 08 31" src="https://user-images.githubusercontent.com/80405708/181915758-769df3fc-466a-4a96-9144-f470c2de72e1.png">
<img width="1266" alt="스크린샷 2022-07-30 22 08 40" src="https://user-images.githubusercontent.com/80405708/181915760-2f6f32a5-f307-4127-8661-b2b69510ebf6.png">
