### ISSUE TITLE
[Feature]보드페이지

### ISSUE THREAD

**Issue by MinsuKim21** [UXMUnderGraduate/22-S-Front#8]
**Description**
router 기본지정이될 홈페이지

---

**TODO**
- [x] 신곡 캐러셀로 보여줌
- [x] 곡정보 리스트를 띄움
- [x] 곡 클릭시 곡에 대한 상세 정보를 띄어줌

---

**ETC**
기타사항
